controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth # retirer le /api en prod
    methods: [ 'POST' ]

api_login_check:
    path: /auth # retirer le /api en prod

api_password_reset_request:
    path: /password-reset # retirer le /api en prod
    controller: App\Controller\PasswordResetController::requestReset
    methods: POST

api_password_reset_confirm:
    path: /password-reset/confirm # retirer le /api en prod
    controller: App\Controller\PasswordResetController::resetPassword
    methods: POST